DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers(
	id INT PRIMARY KEY AUTO_INCREMENT,
	burger_name VARCHAR(50) NOT NULL,
	devoured BOOLEAN NOT NULL,
	date DATETIME DEFAULT 0,
	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
					ON UPDATE CURRENT_TIMESTAMP
);